"""add missing tds_tcs_section columns for 194Q, 206C-1H, 206AA, 206AB

Revision ID: 2dfd7e70dfb6
Revises: de061ac839a5
Create Date: 2026-07-26 21:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfd7e70dfb6'
down_revision: Union[str, None] = 'de061ac839a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tds_tcs_sections', sa.Column('buyer_turnover_threshold', sa.Numeric(18, 2), nullable=True, server_default=sa.text('100000000')))
    op.add_column('tds_tcs_sections', sa.Column('seller_turnover_threshold', sa.Numeric(18, 2), nullable=True, server_default=sa.text('100000000')))
    op.add_column('tds_tcs_sections', sa.Column('override_rate', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('tds_tcs_sections', sa.Column('multiplier', sa.Numeric(3, 1), nullable=True, server_default=sa.text('2.0')))
    op.add_column('tds_tcs_sections', sa.Column('min_rate', sa.Numeric(5, 2), nullable=True, server_default=sa.text('5.0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tds_tcs_sections', 'min_rate')
    op.drop_column('tds_tcs_sections', 'multiplier')
    op.drop_column('tds_tcs_sections', 'override_rate')
    op.drop_column('tds_tcs_sections', 'seller_turnover_threshold')
    op.drop_column('tds_tcs_sections', 'buyer_turnover_threshold')
    # ### end Alembic commands ###
