"""extract recurring_template and payment_allocation models

Revision ID: 3b9d8b02a179
Revises: 0056_abc123_item_type
Create Date: 2026-07-26 18:15:54.487817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b9d8b02a179'
down_revision: Union[str, None] = '0056_abc123_item_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_company_id'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('uq_ag_company_system_code'), table_name='account_groups')
    op.alter_column('asset_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('asset_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('asset_register', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('asset_register', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_bank_recon_company_id'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_recon_ledger_id'), table_name='bank_reconciliations')
    op.create_index(op.f('ix_bank_reconciliations_company_id'), 'bank_reconciliations', ['company_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_ledger_id'), 'bank_reconciliations', ['ledger_id'], unique=False)
    op.drop_index(op.f('ix_bank_stmt_lines_company_id'), table_name='bank_statement_lines')
    op.drop_index(op.f('ix_bank_stmt_lines_ledger_id'), table_name='bank_statement_lines')
    op.create_index(op.f('ix_bank_statement_lines_company_id'), 'bank_statement_lines', ['company_id'], unique=False)
    op.create_index(op.f('ix_bank_statement_lines_ledger_id'), 'bank_statement_lines', ['ledger_id'], unique=False)
    op.alter_column('bill_of_materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bill_of_materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bom_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bom_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bom_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bom_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'constitution',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='proprietorship|partnership|llp|private_limited|public_limited|huf|trust|society|others',
               existing_nullable=True)
    op.alter_column('companies', 'audit_required',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('uq_companies_gstin'), 'companies', type_='unique')
    op.drop_column('companies', 'currency')
    op.alter_column('compliance_reports', 'report_type',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='income_tax|schedule_iii|indas_pl|icai_nce|gst_status',
               existing_nullable=False)
    op.alter_column('compliance_reports', 'format',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='json|pdf|xlsx',
               existing_nullable=False,
               existing_server_default=sa.text("'json'::character varying"))
    op.alter_column('document_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_attachments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gst_challans', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gst_challans', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_gst_returns_period'), table_name='gst_returns')
    op.alter_column('icai_nce_templates', 'statement_type',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='balance_sheet|profit_loss|notes',
               existing_nullable=False)
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('import_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('import_jobs_user_id_fkey'), 'import_jobs', type_='foreignkey')
    op.drop_constraint(op.f('import_jobs_company_id_fkey'), 'import_jobs', type_='foreignkey')
    op.alter_column('income_tax_regime_configs', 'regime',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='old|new',
               existing_nullable=False)
    op.alter_column('income_tax_regime_configs', 'financial_year',
               existing_type=sa.VARCHAR(length=9),
               comment=None,
               existing_comment='e.g. 2025-26',
               existing_nullable=False)
    op.alter_column('income_tax_regime_configs', 'presumptive_section',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='44AD|44ADA|44AE|null',
               existing_nullable=True)
    op.drop_constraint(op.f('income_tax_regime_configs_company_id_regime_financial_year_key'), 'income_tax_regime_configs', type_='unique')
    op.create_unique_constraint('uq_itr_company_regime_fy', 'income_tax_regime_configs', ['company_id', 'regime', 'financial_year'])
    op.alter_column('indas_schedules', 'schedule_part',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='I|II for Schedule III',
               existing_nullable=False)
    op.drop_constraint(op.f('indas_schedules_company_id_system_code_key'), 'indas_schedules', type_='unique')
    op.create_unique_constraint('uq_indas_company_code', 'indas_schedules', ['company_id', 'system_code'])
    op.drop_index(op.f('uq_ledger_company_system_code'), table_name='ledgers')
    op.drop_column('ledgers', 'currency')
    op.drop_index(op.f('ix_loan_payments_loan'), table_name='loan_payments')
    op.drop_index(op.f('ix_loans_company_status'), table_name='loans')
    op.drop_index(op.f('ix_loans_company_type'), table_name='loans')
    op.alter_column('payment_allocations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_allocations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_payment_alloc_invoice'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_alloc_payment'), table_name='payment_allocations')
    op.alter_column('production_order_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_order_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recurring_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recurring_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('routing_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('routing_operations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('routings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('routings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_voucher_lines_hsn_sac_id'), table_name='voucher_lines')
    op.drop_column('voucher_lines', 'fc_credit')
    op.drop_column('voucher_lines', 'fc_debit')
    op.alter_column('voucher_numbering', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('voucher_numbering', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('voucher_numbering_company_id_fkey'), 'voucher_numbering', type_='foreignkey')
    op.drop_index(op.f('ix_vouchers_created_by'), table_name='vouchers')
    op.create_index(op.f('ix_vouchers_company_id'), 'vouchers', ['company_id'], unique=False)
    op.drop_column('vouchers', 'currency')
    op.drop_column('vouchers', 'exchange_rate')
    op.alter_column('work_centers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_centers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_centers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_centers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('vouchers', sa.Column('exchange_rate', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True))
    op.add_column('vouchers', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_vouchers_company_id'), table_name='vouchers')
    op.create_index(op.f('ix_vouchers_created_by'), 'vouchers', ['created_by'], unique=False)
    op.create_foreign_key(op.f('voucher_numbering_company_id_fkey'), 'voucher_numbering', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('voucher_numbering', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('voucher_numbering', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('voucher_lines', sa.Column('fc_debit', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('voucher_lines', sa.Column('fc_credit', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_voucher_lines_hsn_sac_id'), 'voucher_lines', ['hsn_sac_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('routings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('routings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('routing_operations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('routing_operations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('recurring_templates', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recurring_templates', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_orders', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_orders', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_order_lines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('production_order_lines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_payment_alloc_payment'), 'payment_allocations', ['payment_voucher_id'], unique=False)
    op.create_index(op.f('ix_payment_alloc_invoice'), 'payment_allocations', ['invoice_voucher_id'], unique=False)
    op.alter_column('payment_allocations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payment_allocations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_loans_company_type'), 'loans', ['company_id', 'loan_type'], unique=False)
    op.create_index(op.f('ix_loans_company_status'), 'loans', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_loan_payments_loan'), 'loan_payments', ['loan_id'], unique=False)
    op.add_column('ledgers', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=True))
    op.create_index(op.f('uq_ledger_company_system_code'), 'ledgers', ['company_id', 'system_code'], unique=True)
    op.drop_constraint('uq_indas_company_code', 'indas_schedules', type_='unique')
    op.create_unique_constraint(op.f('indas_schedules_company_id_system_code_key'), 'indas_schedules', ['company_id', 'system_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('indas_schedules', 'schedule_part',
               existing_type=sa.VARCHAR(length=10),
               comment='I|II for Schedule III',
               existing_nullable=False)
    op.drop_constraint('uq_itr_company_regime_fy', 'income_tax_regime_configs', type_='unique')
    op.create_unique_constraint(op.f('income_tax_regime_configs_company_id_regime_financial_year_key'), 'income_tax_regime_configs', ['company_id', 'regime', 'financial_year'], postgresql_nulls_not_distinct=False)
    op.alter_column('income_tax_regime_configs', 'presumptive_section',
               existing_type=sa.VARCHAR(length=10),
               comment='44AD|44ADA|44AE|null',
               existing_nullable=True)
    op.alter_column('income_tax_regime_configs', 'financial_year',
               existing_type=sa.VARCHAR(length=9),
               comment='e.g. 2025-26',
               existing_nullable=False)
    op.alter_column('income_tax_regime_configs', 'regime',
               existing_type=sa.VARCHAR(length=10),
               comment='old|new',
               existing_nullable=False)
    op.create_foreign_key(op.f('import_jobs_company_id_fkey'), 'import_jobs', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('import_jobs_user_id_fkey'), 'import_jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('import_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('icai_nce_templates', 'statement_type',
               existing_type=sa.VARCHAR(length=30),
               comment='balance_sheet|profit_loss|notes',
               existing_nullable=False)
    op.create_index(op.f('ix_gst_returns_period'), 'gst_returns', ['period'], unique=False)
    op.alter_column('gst_challans', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gst_challans', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_attachments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('document_attachments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('compliance_reports', 'format',
               existing_type=sa.VARCHAR(length=10),
               comment='json|pdf|xlsx',
               existing_nullable=False,
               existing_server_default=sa.text("'json'::character varying"))
    op.alter_column('compliance_reports', 'report_type',
               existing_type=sa.VARCHAR(length=40),
               comment='income_tax|schedule_iii|indas_pl|icai_nce|gst_status',
               existing_nullable=False)
    op.add_column('companies', sa.Column('currency', sa.VARCHAR(length=3), server_default=sa.text("'INR'::character varying"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_companies_gstin'), 'companies', ['gstin'], postgresql_nulls_not_distinct=False)
    op.alter_column('companies', 'audit_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('companies', 'constitution',
               existing_type=sa.VARCHAR(length=30),
               comment='proprietorship|partnership|llp|private_limited|public_limited|huf|trust|society|others',
               existing_nullable=True)
    op.alter_column('bom_versions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bom_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bom_lines', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bom_lines', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bill_of_materials', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bill_of_materials', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_bank_statement_lines_ledger_id'), table_name='bank_statement_lines')
    op.drop_index(op.f('ix_bank_statement_lines_company_id'), table_name='bank_statement_lines')
    op.create_index(op.f('ix_bank_stmt_lines_ledger_id'), 'bank_statement_lines', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_bank_stmt_lines_company_id'), 'bank_statement_lines', ['company_id'], unique=False)
    op.drop_index(op.f('ix_bank_reconciliations_ledger_id'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_company_id'), table_name='bank_reconciliations')
    op.create_index(op.f('ix_bank_recon_ledger_id'), 'bank_reconciliations', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_bank_recon_company_id'), 'bank_reconciliations', ['company_id'], unique=False)
    op.alter_column('asset_register', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('asset_register', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('asset_categories', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('asset_categories', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('uq_ag_company_system_code'), 'account_groups', ['company_id', 'system_code'], unique=True)
    op.create_table('exchange_rates',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=False),
    sa.Column('rate_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('exchange_rates_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_rates_pkey')),
    sa.UniqueConstraint('company_id', 'currency', 'rate_date', name=op.f('uq_exrate_company_currency_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_exchange_rates_company_id'), 'exchange_rates', ['company_id'], unique=False)
    # ### end Alembic commands ###
