"""add hash chain columns to audit_logs

Revision ID: bd53ce4b6e7c
Revises: 3b9d8b02a179
Create Date: 2026-07-26 18:52:08.018387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd53ce4b6e7c'
down_revision: Union[str, None] = '3b9d8b02a179'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('previous_hash', sa.String(64), nullable=True))
    op.add_column('audit_logs', sa.Column('current_hash', sa.String(64), nullable=True))
    op.create_index('ix_audit_logs_company_created', 'audit_logs', ['company_id', 'created_at'])
    # ### end Alembic commands ###

    # Backfill hash chain for existing records using raw SQL
    import hashlib
    import json

    conn = op.get_bind()

    # Get all companies that have audit logs
    companies = conn.execute(
        sa.text("SELECT DISTINCT company_id FROM audit_logs ORDER BY company_id")
    ).fetchall()

    for (company_id,) in companies:
        # Get all entries for this company in chronological order
        entries = conn.execute(
            sa.text("""
                SELECT id, action, entity_type, entity_id, old_value, new_value, description
                FROM audit_logs
                WHERE company_id = :cid
                ORDER BY created_at ASC
            """),
            {"cid": company_id}
        ).fetchall()

        prev_hash = "0" * 64
        for entry in entries:
            payload = {
                "prev": prev_hash,
                "action": entry.action,
                "entity_type": entry.entity_type,
                "entity_id": entry.entity_id,
                "old_value": entry.old_value,
                "new_value": entry.new_value,
                "description": entry.description,
            }
            payload_str = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
            current_hash = hashlib.sha256(payload_str.encode()).hexdigest()

            conn.execute(
                sa.text("""
                    UPDATE audit_logs
                    SET previous_hash = :prev, current_hash = :curr
                    WHERE id = :id
                """),
                {"prev": prev_hash, "curr": current_hash, "id": entry.id}
            )
            prev_hash = current_hash

    print("Hash chain backfilled for all companies")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_company_created', table_name='audit_logs')
    op.drop_column('audit_logs', 'current_hash')
    op.drop_column('audit_logs', 'previous_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_company_created', table_name='audit_logs')
    op.drop_column('audit_logs', 'current_hash')
    op.drop_column('audit_logs', 'previous_hash')
    # ### end Alembic commands ###
