"""add schedule ii fields to asset_category

Revision ID: bdee030c0ac8
Revises: bd53ce4b6e7c
Create Date: 2026-07-26 19:00:15.271645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdee030c0ac8'
down_revision: Union[str, None] = 'bd53ce4b6e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_categories', sa.Column('schedule_ii_class', sa.String(50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_categories', 'schedule_ii_class')
    # ### end Alembic commands ###
