"""add schedule_ii_class to asset_category

Revision ID: de061ac839a5
Revises: bdee030c0ac8
Create Date: 2026-07-26 19:06:51.865426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de061ac839a5'
down_revision: Union[str, None] = 'bdee030c0ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
