"""add_asset_revaluation_model

Revision ID: e8513d9ca506
Revises: 9e9dd2e46a7c
Create Date: 2026-07-27 15:18:30.129563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8513d9ca506'
down_revision: Union[str, None] = '9e9dd2e46a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # The table was previously created only via `Base.metadata.create_all()`
    # in seed scripts, so a fresh DB had no migration to create it. Create it
    # (if absent) before the timezone ALTERs below; already-stamped DBs skip
    # this migration entirely.
    bind = op.get_bind()
    if not bind.dialect.has_table(bind, "asset_revaluations"):
        op.create_table(
            "asset_revaluations",
            sa.Column("id", sa.String(length=36), primary_key=True),
            sa.Column("company_id", sa.String(length=36), nullable=False),
            sa.Column("asset_id", sa.String(length=36), nullable=False),
            sa.Column("revaluation_date", sa.String(length=10), nullable=False),
            sa.Column("previous_wdv", sa.Float(), nullable=False),
            sa.Column("new_wdv", sa.Float(), nullable=False),
            sa.Column("increase_decrease", sa.Float(), nullable=False),
            sa.Column("reason", sa.String(length=255), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
            sa.ForeignKeyConstraint(["asset_id"], ["asset_register.id"], ondelete="CASCADE"),
        )
        op.create_index("ix_asset_revaluations_company_id", "asset_revaluations", ["company_id"])
        op.create_index("ix_asset_revaluations_asset_id", "asset_revaluations", ["asset_id"])
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_revaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('asset_revaluations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset_revaluations', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('asset_revaluations', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
